config/routes.rb
Rails.application.routes.draw do
  
  devise_for :authors
  #get 'pages/index'
  root to: 'readers/pages#index'
  get '/blog/:id' => 'readers/books#show', as: :blog_book
  scope module: 'authors' do
    resources :books
  end
  # Ex:- scope :active, -> {where(:active => true)}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_one_attached :header_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors/books_controller.rb
module Authors
  class BooksController < AuthorsController
    before_action :set_book, only: [:edit, :update, :destroy]
  
    # GET /books
    def index
      @books = current_author.books
    end
  
    # GET /books/new
    def new
      @book = current_author.books.build
    end
  
    # GET /books/1/edit
    def edit
    end
  
    # POST /books
    def create
      @book = current_author.books.build(book_params)
  
      if @book.save
        redirect_to edit_book_path(@book)
      else
        render :new
      end
    end
  
    # PATCH/PUT /books/1
    def update
      if @book.update(book_params)
        redirect_to edit_book_path(@book)
      else
        render :edit
      end
    end
  
    # DELETE /books/1
    def destroy
      @book.destroy
      redirect_to books_url, notice: 'Book was successfully destroyed.'
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_book
        @book = current_author.books.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def book_params
        params.require(:book).permit(:title, :description, :header_image)
      end
  end
  
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    before_action :authenticate_author!

    layout 'authors'
end

app/controllers/readers/books_controller.rb
module Readers
    class BooksController < ReadersController
        def show
            @book = Book.find(params[:id])
        end
        
    end
end

app/controllers/readers/pages_controller.rb
module Readers
  class PagesController < ReadersController
    def index
      @books = Book.all
    end
  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
    layout 'readers'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/authors/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mt-3">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group mt-3">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group mt-3">
    <%= form.label :header_image %>
    <%= form.file_field :header_image, class: 'form-control' %>
    <div class="mt-1">
      <% if book.header_image.present? %>
        <small>Immagine</small>
        <%= image_tag(book.header_image, width: '100%') %>
      <% end %>
    </div>
  </div>

  <div class="actions d-grid gap-2 mt-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/authors/books/edit.html.erb
<div class="row">
    <div class="col-md-4">
        <%= link_to 'Back', books_path, class: 'btn btn-secondary mb-3' %>
        <div class="card">
            <div class="card-header">
                <h4 class='card-title'>Modifica libro</h4>
            </div>
            <div class="card-body">
                <%= render 'form', book: @book %>
            </div>
        </div>
    </div>
</div>

app/views/authors/books/index.html.erb
<h4 class='d-flex justify-content-between mb-4'>
  <span>Libri</span>
  <%= link_to 'New Book', new_book_path , class: 'btn btn-primary' %>
</h4>

<% @books.each do |book| %>
  <%= link_to edit_book_path(book), class: 'text-decoration-none' do %>
    <div class="card mb-3 book-card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-2">
            <% if book.header_image.present? %>
              <div class="header-img" style="background-image: url(<%= url_for(book.header_image) %>);"></div>
            <% end %>
          </div>
          <div class="col-md-10">
            <h5 class='card-title mb-1 text-dark'><%= book.title %></h5>
            <p class='text-secondary mb-0'><%= book.description %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/authors/books/new.html.erb
<div class="row">
    <div class="col-md-4">
        <%= link_to 'Back', books_path, class: 'btn btn-dark mb-3' %>

        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Nuovo libro</h4>
            </div>
            <div class="card-body">
                <%= render 'form', book: @book %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoustudBooks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/authors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoustudBooks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light authors">
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/layouts/readers.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoustudBooks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light readers <%= controller_name %> <%= action_name %>">
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/readers/books/show.html.erb
<div class="row">
    <div class="col-lg-4 offset-lg-4">
        <div class="card book-card">
            <div class="header-image" style="background-image: url(<%= url_for(@book.header_image) %>)">
            </div>
            <div class="card-body">
                <h1 class="card-title"><%= @book.title %></h1>
                <p class="card-text"><%= @book.description %></p>
            </div>
        </div>
    </div>
</div>

app/views/readers/pages/index.html.erb
<div class="row">
    <% @books.each do |book| %>
        <div class="col-md-6 mt-3 col-lg-4">
            <div class="card book-card">
                <div class="header-image" style="background-image: url(<%= url_for(book.header_image) %>)">
                </div>
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title"><%= book.title %></h5>
                    <p class="card-text"><%= truncate(book.description, length: 300) %></p>
                    <%= link_to "Scopri di più", blog_book_path(book), class: 'btn btn-primary mt-auto d-grid gap-2 mt-3' %>
                </div>
            </div>
        </div>
    <% end %>
</div>